import type React from 'react';

// ── Colors ──
export const C = {
  red: '#C8102E',
  redBright: '#E8213F',
  redDark: '#A00D24',
  navy: '#0C1B37',
  teal: '#80CBA2',
  green: '#1B9E5A',
  amber: '#D97706',
  blue: '#3B82F6',
  bg: '#F7F6F3',
  bgCard: '#FFFFFF',
  bgSubtle: '#EEEDEA',
  bgMuted: '#E5E4E0',
  textPrimary: '#1A1A1A',
  textSecondary: '#4A4A4A',
  textTertiary: '#8A8A8A',
  textMuted: '#B0B0B0',
};

// ── Quadrant colors ──
export const QUADRANT = {
  tactical: C.red,
  technical: C.green,
  physical: C.amber,
  mental: C.blue,
};

// ── Slide dimensions (16:9 landscape, matching reference 1440x809) ──
export const PAGE_WIDTH = 1440;
export const PAGE_HEIGHT = 809;

// ── Google Fonts link (injected once) ──
export const FONTS_HREF =
  'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap';

// ── Botafogo shield path (public) ──
export const BFSA_SHIELD = '/3154_imgbank_1685113109.png';

export function injectFonts() {
  if (document.querySelector(`link[href="${FONTS_HREF}"]`)) return;
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = FONTS_HREF;
  document.head.appendChild(link);
}

// ── Page Styles ──
export const styles: Record<string, React.CSSProperties> = {
  page: {
    background: C.bg,
    minHeight: '100vh',
    fontFamily: "'DM Sans', sans-serif",
    display: 'flex',
    flexDirection: 'column',
    overflowX: 'hidden',
  },
  toolbar: {
    position: 'sticky',
    top: 0,
    zIndex: 20,
    background: 'rgba(247, 246, 243, 0.92)',
    backdropFilter: 'blur(12px)',
    borderBottom: `1px solid ${C.bgMuted}`,
    padding: '12px 0',
    marginBottom: 24,
  },
  toolbarInner: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: '0 24px',
    display: 'flex',
    gap: 12,
    alignItems: 'flex-end',
    flexWrap: 'wrap',
  },
  searchGroup: {
    position: 'relative',
    flex: 1,
    minWidth: 160,
  },
  searchLabel: {
    display: 'block',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 10,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: C.textTertiary,
    marginBottom: 4,
  },
  searchWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: C.bgCard,
    border: `1px solid ${C.bgMuted}`,
    borderRadius: 8,
    padding: '8px 12px',
  },
  searchInput: {
    border: 'none',
    outline: 'none',
    background: 'transparent',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 13,
    color: C.textPrimary,
    flex: 1,
    minWidth: 0,
  },
  dropdown: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    background: C.bgCard,
    border: `1px solid ${C.bgMuted}`,
    borderRadius: 8,
    boxShadow: '0 8px 24px rgba(0,0,0,0.1)',
    zIndex: 30,
    maxHeight: 280,
    overflowY: 'auto',
    marginTop: 4,
  },
  dropdownItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    padding: '10px 14px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'background 0.15s',
    borderBottom: `1px solid ${C.bgSubtle}`,
  },
  dropdownName: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 13,
    fontWeight: 500,
    color: C.textPrimary,
  },
  dropdownMeta: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 11,
    color: C.textTertiary,
  },
  printBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    background: C.red,
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '10px 20px',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    letterSpacing: '0.04em',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  report: {
    padding: '0 24px 60px',
    flexGrow: 1,
    overflowX: 'hidden',
    boxSizing: 'border-box',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 400,
    gap: 16,
  },
  emptyText: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 14,
    color: C.textTertiary,
    textAlign: 'center',
  },
  loadingState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 400,
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 28,
  },
  grid2x2: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 28,
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: 28,
  },
  card: {
    background: C.bgCard,
    border: `1px solid ${C.bgMuted}`,
    borderRadius: 12,
    padding: '24px 28px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04)',
  },
  cardElevated: {
    background: C.bgCard,
    border: `1px solid ${C.bgMuted}`,
    borderRadius: 12,
    padding: '24px 28px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.06)',
  },
  cardTitle: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 18,
    fontWeight: 600,
    color: C.textPrimary,
    marginTop: 0,
    marginBottom: 18,
  },
  idGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
  },
  idRow: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '10px 0',
    borderBottom: `1px solid ${C.bgSubtle}`,
  },
  idLabel: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 14,
    color: C.textTertiary,
    fontWeight: 500,
  },
  idValue: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 15,
    color: C.textPrimary,
    fontWeight: 600,
  },
  verdictLabel: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: C.textTertiary,
    marginBottom: 10,
  },
  verdictText: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 14,
    color: C.textSecondary,
    lineHeight: 1.6,
    margin: 0,
    outline: 'none',
  },
  quadrantLabel: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 14,
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    marginBottom: 14,
  },
  bulletList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  bulletItem: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 15,
    color: C.textSecondary,
    lineHeight: 1.5,
    paddingLeft: 16,
    position: 'relative',
    outline: 'none',
  },
  eliteSummary: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    marginBottom: 24,
    padding: '16px 22px',
    background: C.bgSubtle,
    borderRadius: 10,
  },
  eliteCount: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 32,
    fontWeight: 700,
    color: C.green,
  },
  eliteSummaryText: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 15,
    color: C.textSecondary,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 14,
  },
  th: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 12,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: C.textTertiary,
    padding: '10px 14px',
    textAlign: 'left',
    borderBottom: `2px solid ${C.bgMuted}`,
  },
  td: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 14,
    color: C.textPrimary,
    padding: '10px 14px',
  },
  pBadge: {
    display: 'inline-block',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 13,
    fontWeight: 700,
    padding: '3px 10px',
    borderRadius: 12,
  },
  placeholder: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 15,
    color: C.textTertiary,
    fontStyle: 'italic',
    textAlign: 'center',
    padding: '24px 0',
  },
  physTitle: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 18,
    fontWeight: 600,
    color: C.textPrimary,
    marginTop: 0,
    marginBottom: 18,
  },
  editablePlaceholder: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 14,
    color: C.textMuted,
    padding: '16px',
    borderRadius: 8,
    border: `1px dashed ${C.bgMuted}`,
    outline: 'none',
    minHeight: 80,
  },
  similarRow: {
    display: 'grid',
    gridTemplateColumns: '36px 1fr 56px 100px',
    alignItems: 'center',
    gap: 14,
    padding: '14px 0',
    borderBottom: `1px solid ${C.bgSubtle}`,
  },
  similarRank: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: C.bgSubtle,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 14,
    fontWeight: 700,
    color: C.textSecondary,
  },
  similarName: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 16,
    fontWeight: 600,
    color: C.textPrimary,
  },
  similarClub: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 13,
    color: C.textTertiary,
  },
  similarPct: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 15,
    fontWeight: 700,
    color: C.green,
    textAlign: 'right',
  },
  progressTrack: {
    height: 6,
    background: C.bgSubtle,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    background: C.green,
    borderRadius: 3,
    transition: 'width 0.6s ease',
  },
  obsLabel: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 12,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: C.textTertiary,
    marginBottom: 8,
  },
  obsField: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 14,
    color: C.textSecondary,
    padding: '14px 18px',
    borderRadius: 8,
    border: `1px solid ${C.bgMuted}`,
    outline: 'none',
    lineHeight: 1.5,
    minHeight: 60,
  },
  conclusionText: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 15,
    color: C.textSecondary,
    lineHeight: 1.6,
    outline: 'none',
  },
  recBanner: {
    marginTop: 28,
    background: `linear-gradient(135deg, ${C.red}, ${C.redDark})`,
    borderRadius: 14,
    padding: '28px 36px',
    boxShadow: '0 8px 24px rgba(200, 16, 46, 0.25)',
  },
  recTitle: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    color: 'rgba(255,255,255,0.6)',
    marginBottom: 10,
  },
  recText: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 16,
    color: '#fff',
    lineHeight: 1.6,
    fontWeight: 500,
    outline: 'none',
  },
  quoteBox: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 14,
    color: C.textSecondary,
    fontStyle: 'italic',
    padding: '18px 24px',
    borderLeft: `4px solid ${C.teal}`,
    background: C.bgSubtle,
    borderRadius: '0 10px 10px 0',
    outline: 'none',
    lineHeight: 1.5,
  },
  analysisHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    marginBottom: 20,
    paddingBottom: 16,
    borderBottom: `2px solid ${C.red}`,
  },
  analysisLabel: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: C.red,
  },
  analysisPlayerName: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 24,
    fontWeight: 600,
    lineHeight: 1.15,
    color: C.textPrimary,
  },
  modeloBadge: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 11,
    fontWeight: 600,
    padding: '5px 14px',
    borderRadius: 14,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    marginLeft: 'auto',
  },
  scoresGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
    gap: 16,
    marginBottom: 24,
  },
  scoreBox: {
    background: C.bgSubtle,
    borderRadius: 10,
    padding: '14px 12px',
    textAlign: 'center' as const,
    border: `1px solid ${C.bgMuted}`,
  },
  scoreLabel: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    color: C.textTertiary,
    marginBottom: 6,
  },
  scoreValue: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 28,
    fontWeight: 700,
    lineHeight: 1.1,
  },
  analysisText: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 17,
    color: C.textSecondary,
    lineHeight: 1.75,
    textAlign: 'justify' as const,
    outline: 'none',
    padding: '20px 24px',
    background: C.bgSubtle,
    borderRadius: 10,
    border: `1px solid ${C.bgMuted}`,
    marginBottom: 16,
  },
  financialRow: {
    display: 'flex',
    gap: 14,
    flexWrap: 'wrap' as const,
  },
  financialTag: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 13,
    color: C.textPrimary,
    padding: '8px 16px',
    background: C.bgSubtle,
    borderRadius: 8,
    border: `1px solid ${C.bgMuted}`,
  },
  legendBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    padding: '12px 16px',
    background: C.bgSubtle,
    borderRadius: 8,
    border: `1px solid ${C.bgMuted}`,
    marginBottom: 16,
  },
  legendEntry: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 12,
    color: C.textTertiary,
    lineHeight: 1.5,
  },
  scTag: {
    fontFamily: "'DM Sans', sans-serif",
    fontSize: 12,
    color: C.textSecondary,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 14px',
    background: 'rgba(128, 203, 162, 0.1)',
    border: '1px solid rgba(128, 203, 162, 0.3)',
    borderRadius: 6,
  },
};
